# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`

general {
  border_size = 2
}

misc:vrr = 2

decoration {
  # Generic settings for tiles
  active_opacity = 0.80
  inactive_opacity = 0.70
  blur {
    new_optimizations = on
    ignore_opacity = on
    vibrancy = 0.0
    contrast = 1.0
    brightness = 1.1
  }
}
