$primary_paletteKeyColor = 5873c4
$secondary_paletteKeyColor = 71768b
$tertiary_paletteKeyColor = 8e6c8a
$neutral_paletteKeyColor = 777777
$neutral_variant_paletteKeyColor = 777777
$background = 131313
$onBackground = e2e2e2
$surface = 131313
$surfaceDim = 131313
$surfaceBright = 393939
$surfaceContainerLowest = 0e0e0e
$surfaceContainerLow = 1b1b1b
$surfaceContainer = 1f1f1f
$surfaceContainerHigh = 2a2a2a
$surfaceContainerHighest = 353535
$onSurface = e2e2e2
$surfaceVariant = 474747
$onSurfaceVariant = c6c6c6
$inverseSurface = e2e2e2
$inverseOnSurface = 303030
$outline = 919191
$outlineVariant = 474747
$shadow = 000000
$scrim = 000000
$surfaceTint = b4c5ff
$primary = b4c5ff
$onPrimary = 002a78
$primaryContainer = 234290
$onPrimaryContainer = dbe1ff
$inversePrimary = 3e5aa9
$secondary = c1c5dd
$onSecondary = 2b3042
$secondaryContainer = 414659
$onSecondaryContainer = dde1f9
$tertiary = e2bbdb
$onTertiary = 422741
$tertiaryContainer = a986a4
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = dbe1ff
$primaryFixedDim = b4c5ff
$onPrimaryFixed = 00174b
$onPrimaryFixedVariant = 234290
$secondaryFixed = dde1f9
$secondaryFixedDim = c1c5dd
$onSecondaryFixed = 161b2c
$onSecondaryFixedVariant = 414659
$tertiaryFixed = ffd6f8
$tertiaryFixedDim = e2bbdb
$onTertiaryFixed = 2b122b
$onTertiaryFixedVariant = 5a3d58
$term0 = 353434
$term1 = 967cff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 91acd6
$term5 = a7a2ee
$term6 = 9cceff
$term7 = e8d3de
$term8 = ac9fa9
$term9 = af9aff
$term10 = 89ecff
$term11 = fff0f6
$term12 = b0c2db
$term13 = bfb8f7
$term14 = bae0ff
$term15 = ffffff
$rosewater = f5eff9
$flamingo = e5dff4
$pink = dbd9ff
$mauve = b3bcff
$red = b3aaff
$maroon = c0b8f0
$peach = e0c2f9
$yellow = ffecf3
$green = c8e3ff
$teal = cde1ff
$sky = c9dcff
$sapphire = acc8ff
$blue = a3bbff
$lavender = becbff
$klink = 6286d0
$klinkSelection = 6286d0
$kvisited = 6d77dd
$kvisitedSelection = 6e77dd
$knegative = 8872ff
$knegativeSelection = 8972ff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 4ab0ff
$kpositiveSelection = 4bb0ff
$text = e2e2e2
$subtext1 = c6c6c6
$subtext0 = 919191
$overlay2 = 7e7e7e
$overlay1 = 6b6b6b
$overlay0 = 595959
$surface2 = 484848
$surface1 = 373737
$surface0 = 252525
$base = 131313
$mantle = 131313
$crust = 121212
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
