$primary_paletteKeyColor = 5c73c4
$secondary_paletteKeyColor = 72768b
$tertiary_paletteKeyColor = 8f6c89
$neutral_paletteKeyColor = 777777
$neutral_variant_paletteKeyColor = 777777
$background = 131313
$onBackground = e2e2e2
$surface = 131313
$surfaceDim = 131313
$surfaceBright = 393939
$surfaceContainerLowest = 0e0e0e
$surfaceContainerLow = 1b1b1b
$surfaceContainer = 1f1f1f
$surfaceContainerHigh = 2a2a2a
$surfaceContainerHighest = 353535
$onSurface = e2e2e2
$surfaceVariant = 474747
$onSurfaceVariant = c6c6c6
$inverseSurface = e2e2e2
$inverseOnSurface = 303030
$outline = 919191
$outlineVariant = 474747
$shadow = 000000
$scrim = 000000
$surfaceTint = b6c4ff
$primary = b6c4ff
$onPrimary = 092978
$primaryContainer = 284190
$onPrimaryContainer = dce1ff
$inversePrimary = 4259a9
$secondary = c2c5dd
$onSecondary = 2b3042
$secondaryContainer = 44485b
$onSecondaryContainer = dee1f9
$tertiary = e3bada
$onTertiary = 43273f
$tertiaryContainer = aa85a3
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = dce1ff
$primaryFixedDim = b6c4ff
$onPrimaryFixed = 001550
$onPrimaryFixedVariant = 284190
$secondaryFixed = dee1f9
$secondaryFixedDim = c2c5dd
$onSecondaryFixed = 161b2c
$onSecondaryFixedVariant = 424659
$tertiaryFixed = ffd7f5
$tertiaryFixedDim = e3bada
$onTertiaryFixed = 2c122a
$onTertiaryFixedVariant = 5b3d57
$term0 = 353434
$term1 = 997bff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 92acd6
$term5 = a9a2ed
$term6 = 9dceff
$term7 = e8d3de
$term8 = ac9fa9
$term9 = b199ff
$term10 = 89ecff
$term11 = fff0f6
$term12 = b1c2db
$term13 = c0b7f7
$term14 = bae0ff
$term15 = ffffff
$rosewater = f5eff9
$flamingo = e5dff4
$pink = dcd9ff
$mauve = b5bbff
$red = b4a9ff
$maroon = c1b8ef
$peach = e0c2f9
$yellow = ffecf3
$green = c8e3ff
$teal = cee1ff
$sky = cadcff
$sapphire = adc7ff
$blue = a5bbff
$lavender = bfcaff
$klink = 6585d1
$klinkSelection = 6585d1
$kvisited = 7176dd
$kvisitedSelection = 7176dd
$knegative = 8d70ff
$knegativeSelection = 8d70ff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 52afff
$kpositiveSelection = 52afff
$text = e2e2e2
$subtext1 = c6c6c6
$subtext0 = 919191
$overlay2 = 7e7e7e
$overlay1 = 6b6b6b
$overlay0 = 595959
$surface2 = 484848
$surface1 = 373737
$surface0 = 252525
$base = 131313
$mantle = 131313
$crust = 121212
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
