$background = 131313
$onBackground = e2e2e2
$surface = 131313
$surfaceDim = 131313
$surfaceBright = 393939
$surfaceContainerLowest = 0e0e0e
$surfaceContainerLow = 1b1b1b
$surfaceContainer = 1f1f1f
$surfaceContainerHigh = 2a2a2a
$surfaceContainerHighest = 353535
$onSurface = e2e2e2
$surfaceVariant = 474747
$onSurfaceVariant = c6c6c6
$outline = 919191
$outlineVariant = 474747
$inverseSurface = e2e2e2
$inverseOnSurface = 303030
$shadow = 000000
$scrim = 000000
$surfaceTint = 89d990
$primary = 89d990
$primaryDim = acfeb1
$onPrimary = 003912
$primaryContainer = 00531e
$onPrimaryContainer = a4f5a9
$inversePrimary = 1c6c30
$primaryFixed = a4f5a9
$primaryFixedDim = 89d990
$onPrimaryFixed = 002108
$onPrimaryFixedVariant = 00531e
$secondary = b8ccb5
$secondaryDim = d4e8d0
$onSecondary = 243424
$secondaryContainer = 3a4b3a
$onSecondaryContainer = d4e8d0
$secondaryFixed = d4e8d0
$secondaryFixedDim = b8ccb5
$onSecondaryFixed = 0f1f11
$onSecondaryFixedVariant = 3a4b3a
$tertiary = a1ced6
$tertiaryDim = bae8f0
$onTertiary = 00363d
$tertiaryContainer = 1f4d54
$onTertiaryContainer = bdeaf3
$tertiaryFixed = bdeaf3
$tertiaryFixedDim = a1ced6
$onTertiaryFixed = 001f24
$onTertiaryFixedVariant = 1f4d54
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 398647
$secondaryPaletteKeyColor = 6a7c68
$tertiaryPaletteKeyColor = 527e85
$neutralPaletteKeyColor = 777777
$neutralVariantPaletteKeyColor = 777777
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 398647
$secondary_paletteKeyColor = 6a7c68
$tertiary_paletteKeyColor = 527e85
$neutral_paletteKeyColor = 777777
$neutral_variant_paletteKeyColor = 777777
$term0 = 343433
$term1 = 7a9d00
$term2 = 98dd83
$term3 = bef691
$term4 = 83b694
$term5 = c6a844
$term6 = 9ed7a0
$term7 = d4dbc8
$term8 = a0a596
$term9 = 8db700
$term10 = 9ef289
$term11 = dcffbf
$term12 = acc8af
$term13 = cec06b
$term14 = aceaaa
$term15 = ffffff
$rosewater = f2f2e4
$flamingo = e3e4c5
$pink = ffd79d
$mauve = 5bd0df
$red = c5b542
$maroon = c6c177
$peach = bed696
$yellow = e3f8d0
$green = aef0af
$teal = b1eec0
$sky = a3eac0
$sapphire = 83d8af
$blue = 67cfac
$lavender = 89dcc6
$klink = 239873
$klinkSelection = 239873
$kvisited = 008ca9
$kvisitedSelection = 008ca9
$knegative = 838f00
$knegativeSelection = 838f00
$kneutral = 83bb1d
$kneutralSelection = 83bb1d
$kpositive = 4dbf67
$kpositiveSelection = 4dbf67
$text = e2e2e2
$subtext1 = c6c6c6
$subtext0 = 919191
$overlay2 = 7e7e7e
$overlay1 = 6b6b6b
$overlay0 = 595959
$surface2 = 484848
$surface1 = 373737
$surface0 = 252525
$base = 131313
$mantle = 131313
$crust = 121212
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
