$primary_paletteKeyColor = a56383
$secondary_paletteKeyColor = 8c6f7b
$tertiary_paletteKeyColor = 9b6d50
$neutral_paletteKeyColor = 807478
$neutral_variant_paletteKeyColor = 827378
$background = 191114
$onBackground = eedfe3
$surface = 191114
$surfaceDim = 191114
$surfaceBright = 40373a
$surfaceContainerLowest = 130c0f
$surfaceContainerLow = 21191d
$surfaceContainer = 251d21
$surfaceContainerHigh = 30282b
$surfaceContainerHighest = 3b3236
$onSurface = eedfe3
$surfaceVariant = 504348
$onSurfaceVariant = d4c2c8
$inverseSurface = eedfe3
$inverseOnSurface = 372e31
$outline = 9d8d92
$outlineVariant = 504348
$shadow = 000000
$scrim = 000000
$surfaceTint = fdb0d3
$primary = fdb0d3
$onPrimary = 521d3a
$primaryContainer = 6d3351
$onPrimaryContainer = ffd8e7
$inversePrimary = 884a6a
$secondary = e0bdcb
$onSecondary = 412a34
$secondaryContainer = 5b424d
$onSecondaryContainer = fdd9e7
$tertiary = f2bb99
$onTertiary = 4a2810
$tertiaryContainer = b78668
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffd8e7
$primaryFixedDim = fdb0d3
$onPrimaryFixed = 380725
$onPrimaryFixedVariant = 6d3351
$secondaryFixed = fdd9e7
$secondaryFixedDim = e0bdcb
$onSecondaryFixed = 2a151f
$onSecondaryFixedVariant = 59404b
$tertiaryFixed = ffdbc7
$tertiaryFixedDim = f2bb99
$onTertiaryFixed = 301401
$onTertiaryFixedVariant = 643e24
$term0 = 353434
$term1 = ff479b
$term2 = ffbabd
$term3 = ffdee1
$term4 = b3a2d5
$term5 = e690b9
$term6 = ffba93
$term7 = eed1d4
$term8 = b39ea0
$term9 = ff7faf
$term10 = ffd3d3
$term11 = fff1f1
$term12 = babfdd
$term13 = f6a9c9
$term14 = ffd1c0
$term15 = ffffff
$rosewater = ffedf0
$flamingo = fbd9e3
$pink = ffd0e6
$mauve = fba5dd
$red = f995c1
$maroon = f0abc6
$peach = ffbccb
$yellow = ffedee
$green = ffd8c5
$teal = dedcff
$sky = ebd1ff
$sapphire = f0b3f4
$blue = eea4e6
$lavender = fab8eb
$klink = b36fb3
$klinkSelection = b36fb3
$kvisited = c15e9f
$kvisitedSelection = c15e9f
$knegative = e54f95
$knegativeSelection = e54f95
$kneutral = ff83a7
$kneutralSelection = ff83a7
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = eedfe3
$subtext1 = d4c2c8
$subtext0 = 9d8d92
$overlay2 = 897a7f
$overlay1 = 75676c
$overlay0 = 63565a
$surface2 = 514549
$surface1 = 3f3538
$surface0 = 2c2326
$base = 191114
$mantle = 191114
$crust = 181013
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
